### ISSUE TITLE
play-audio 报错

### ISSUE THREAD

**Issue by liuxing-moresec** [MoresecFE/utils#15]
$audio.play() 的 返回打印是 undefined .catch 方法报错
我看 lib.dom.d.ts 对于  play的 ts定义是 play(): Promise<void>;

**Comment by ohhoney1** [comment]
> $audio.play() 的 返回打印是 undefined .catch 方法报错
> 我看 lib.dom.d.ts 对于 play的 ts定义是 play(): Promise;

看下官方文档，怎么测试含有dom结构的case.
[https://jestjs.io/docs/zh-Hans/tutorial-jquery](https://jestjs.io/docs/zh-Hans/tutorial-jquery)
